package node_error

import "errors"

var (
	ErrUnauthorized                  = errors.New("unauthorized")
	ErrForbidden                     = errors.New("forbidden")
	ErrInvalidAccessCode             = errors.New("access code is not valid")
	ErrTooManyAttempts               = errors.New("too many login attempts, please wait")
	ErrExamNotLoaded                 = errors.New("no exam bundle has been loaded on this node")
	ErrExamContentNotReady           = errors.New("exam content is not ready")
	ErrExamNotOpen                   = errors.New("exam is not open for attempts")
	ErrMaxAttemptsReached            = errors.New("maximum exam attempts reached")
	ErrAttemptNotFound               = errors.New("exam attempt not found")
	ErrAttemptExpired                = errors.New("exam attempt has expired")
	ErrAttemptLocked                 = errors.New("exam attempt is no longer accepting answers")
	ErrAttemptDeviceMismatch         = errors.New("exam attempt is bound to another device")
	ErrAttemptDeviceIDInvalid        = errors.New("exam attempt device id is invalid")
	ErrStaleAnswerWrite              = errors.New("a newer answer for this item has already been saved")
	ErrItemNotFound                  = errors.New("exam item not found")
	ErrParticipantNotFound           = errors.New("participant not found")
	ErrResultNotAvailable            = errors.New("exam result is not available yet")
	ErrAttemptResetOperationNotFound = errors.New("exam attempt reset operation not found")
	ErrAttemptResetConflict          = errors.New("exam attempt reset command conflicts with current state")
	ErrAttemptResetNotAllowed        = errors.New("exam attempt cannot be reset")
	ErrAttemptResetExpired           = errors.New("exam attempt reset command has expired")
	ErrAttemptResetFenced            = errors.New("exam deployment is fenced")
	ErrIntegrityFlood                = errors.New("too many integrity events for this attempt")
	ErrBundleChecksum                = errors.New("bundle checksum does not match its content")
	ErrBundleFileUpload              = errors.New("file_upload items are not supported on the node")
	ErrBundleRosterImmutable         = errors.New("exam bundle cannot replace a baseline after roster synchronization")
	ErrPreflightFailed               = errors.New("node preflight checks failed")
	ErrRepositoryUnavailable         = errors.New("repository unavailable")
	ErrRosterReceiptNotFound         = errors.New("roster event receipt not found")
	ErrRosterPayloadConflict         = errors.New("roster event payload conflicts with stored receipt")
	ErrRosterRevisionGap             = errors.New("roster revision gap")
	ErrRosterDeploymentMismatch      = errors.New("roster event belongs to another deployment")
	ErrRosterExamFenced              = errors.New("exam deployment is fenced")
	ErrRosterExpired                 = errors.New("roster event has expired")
	ErrRosterCodeConflict            = errors.New("roster access code conflicts with an existing participant")
	ErrRosterInvalid                 = errors.New("invalid roster event")
)
